_target_: src.datamodules.BENCHMARK_datamodule.BenchmarkDataModule

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
backbone: 18
label_class: 0
num_workers: 0
pin_memory: False
MSCL: ${MSCL}
dataset: "svhn"