# @package _global_

hydra:
  run:
    dir: logs/experiments/runs/${name}/${now:%Y-%m-%d}_${now:%H-%M}
  sweep:
    dir: logs/experiments/multiruns/${name}/${now:%Y-%m-%d}_${now:%H-%M}
    subdir: ${hydra.job.num}
